config/routes.rb
Rails.application.routes.draw do
  root 'types#index'

  resources :types do
    resources :businesses
  end
end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :type
  validates :name, :presence => true

end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :businesses
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def new
    @type = Type.find(params[:type_id])
    @business = @type.businesses.new
  end

  def create
    @type = Type.find(params[:type_id])
    @business = @type.businesses.new(business_params)
    if @business.save
      redirect_to type_path(@type)
    else
      render :new
    end
  end

  def show
    @type = Type.find(params[:type_id])
    @business = @type.businesses.find(params[:id])
  end

  def destroy
    @type = Type.find(params[:type_id])
    @business = @type.businesses.find(params[:id])
    @business.destroy
    redirect_to type_path(@type)
  end

  def edit
    @type = Type.find(params[:type_id])
    @business = @type.businesses.find(params[:id])
  end

  def update
    @type = Type.find(params[:type_id])
    @business = @type.businesses.find(params[:id])
    if @business.update(business_params)
      redirect_to type_path(@type)
    else
      render :edit
    end
  end

  private

  def business_params
    params.require(:business).permit(:name, :description, :address)
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @types = Type.all
    render :index
  end

  def show
  @type = Type.find(params[:id])
  @businesses = @type.businesses
  render :show
end

  def new
    @type = Type.new
  end

  def create
    @type = Type.new(type_params)
    if @type.save
      redirect_to types_path
    else
      render :new
    end
  end

  private

  def type_params
    params.require(:type).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/businesses/_form.html.erb
<%= form_for [@type, @business] do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :description %><br>
  <%= f.text_field :description %><br>
  <%= f.label :address %><br>
  <%= f.text_field :address %><br>

  <%= f.submit %>
<% end %>

app/views/businesses/edit.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <%= render 'form' %>
</div>

app/views/businesses/new.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <h4>New <%= @type.name %>:</h4>

  <%= render 'form' %>

</div>

app/views/businesses/show.html.erb
<h3 class="text-center"><%= @business.name %></h3>

<p><%= @business.description %></p>
<p><%= @business.address %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikipages</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <h1 class="page-header text-center">
        <%= link_to 'The Purple Pages', types_path %>
      </h1>

      <div class="col-sm-6 col-sm-offset-3">
        <%= yield %>
      </div>

    </div>
  </div>
</body>
</html>

app/views/types/_form.html.erb
<%= form_for @type do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/types/index.html.erb
<%= link_to 'Add a business type', new_type_path, class: "btn btn-default stretch" %>

<h4>Business Types:</h4>

<ul class="list-unstyled">
  <% @types.each do |type| %>
    <li>
      <%= link_to type.name, type_path(type) %>
    </li>
  <% end %>
</ul>

app/views/types/new.html.erb
<h4>New business type:</h4>

<%= render 'form' %>

app/views/types/show.html.erb
<%= link_to 'Add a business', new_type_business_path(@type), class: "btn btn-default stretch" %>

<h4><%= @type.name %> Businesses:</h4>

<ul class="list-unstyled businesses-list">
  <% @businesses.each do |business| %>
    <%= link_to type_business_path(@type, business) do %>
      <li>
        <span class="name"><%= business.name %></span>

        <%= link_to ' Delete', type_business_path(@type, business), data: {confirm: "Are you sure?", method: "delete"}, class: "text-danger delete" %>

        <%= link_to 'Edit', edit_type_business_path(@type, business), class: "edit" %>
      </li>
    <% end %>
  <% end %>
</ul>